# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'FlashUI' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  pod 'FlashUI', :path => '../'

  target 'FlashUITests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'FlashUIUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
